kind: pipeline
name: check-style

trigger:
  ref:
    include:
    - refs/pull/**
    - refs/tags/**
    - refs/heads/master

platform:
  os: linux
  arch: amd64

steps:
- name: yapf
  image: bender:5000/doc_build:akida-gpu_tf260
  commands:
  - pip install -U yapf
  - yapf --style="{based_on_style:google}" -dr examples/
---
kind: pipeline
name: build-doc

trigger:
  ref:
    include:
    - refs/pull/**
    - refs/tags/**
    - refs/heads/master

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: bender:5000/doc_build:akida-gpu_tf260
  commands:
  - pip install -r requirements.txt
  - sphinx-build -D plot_gallery=1 -b html ./doc ./build

- name: update_gh_pages
  image: bender:5000/drone/git:linux
  when:
    ref:
      exclude:
      - refs/pull/**
  commands:
  - git fetch
  - git checkout gh-pages
  - git clean -xf
  - rm -rf _* examples/ api_reference/ user_guide/
  - rm *.html *.inv *.js
  - cp -R ./build/* .
  - rm -Rf doc/ build/
  - rm -rf _sources/
  - git add .
  - git diff --quiet && git diff --staged --quiet || git commit -am "Automated tutorials push"
  - git push origin gh-pages

node:
  hw: gpu

depends_on:
  - check-style

---

# This pipeline runs examples using the latest internal RC versions of
# akida/cnn2snn/akida_models, available on bender
kind: pipeline
name: run-examples-latest-versions

trigger:
  cron:
    - nightly

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: bender:5000/doc_build:akida-gpu_tf260
  commands:
  - pip install -r requirements.txt
  - pip install --index-url http://bender.brainchipinc.local:81/ --trusted-host bender.brainchipinc.local --pre -U cnn2snn
  - pip install --index-url http://bender.brainchipinc.local:81/ --trusted-host bender.brainchipinc.local --pre -U akida_models
  - sphinx-build -D plot_gallery=1 -b html ./doc ./build

node:
  hw: gpu
