kind: pipeline
name: check-style

trigger:
  ref:
    include:
    - refs/pull/**
    - refs/tags/**
    - refs/heads/main

platform:
  os: linux
  arch: amd64

defs:
  image: &image bender:5000/doc_build_tf2.12:akida-gpu_tf212

steps:
- name: report host name
  image: *image
  commands:
  - printenv DRONE_STAGE_MACHINE

- name: flake8
  image: *image
  commands:
  - pip install flake8==4.0.1
  - flake8 --ignore E402,E501 examples/
  # refer to https://flake8.pycqa.org/en/2.6.0/warnings.html for error codes
  # E402: module level import not at top of file
  # E501: line too long

---
kind: pipeline
name: build-doc

trigger:
  ref:
    include:
    - refs/pull/**
    - refs/tags/**
    - refs/heads/main

platform:
  os: linux
  arch: amd64

defs:
  image: &image bender:5000/doc_build_tf2.12:akida-gpu_tf212

steps:
- name: report host name
  image: *image
  commands:
  - printenv DRONE_STAGE_MACHINE

- name: build
  image: *image
  privileged: true
  commands:
  - pip install -r requirements.txt
  - sphinx-build -D plot_gallery=1 -b html ./doc ./build
  volumes:
    - name: akida_chip
      path: /dev/akida0

- name: update_gh_pages
  image: bender:5000/drone/git:linux
  when:
    ref:
      exclude:
      - refs/pull/**
    cron:
      exclude:
      - nightly-build
  commands:
  - git fetch
  - git checkout gh-pages
  - git clean -xf
  - rm -rf _* examples/ api_reference/ user_guide/
  - rm *.html *.inv *.js
  - cp -R ./build/* .
  - rm -Rf doc/ build/
  - rm -rf _sources/
  - git add .
  - git diff --quiet && git diff --staged --quiet || git commit -am "Automated tutorials push"
  - git push origin gh-pages

volumes:
- name: akida_chip
  host:
    path: /dev/akida0

node:
  hw: gpu-nsoc_v2

depends_on:
  - check-style

---

# This pipeline runs examples using the latest internal RC versions of
# akida/cnn2snn/akida_models, available on bender
kind: pipeline
name: run-examples-latest-versions

trigger:
  cron:
    - nightly

platform:
  os: linux
  arch: amd64

defs:
  image: &image bender:5000/doc_build_tf2.12:akida-gpu_tf212

steps:
- name: report host name
  image: *image
  commands:
  - printenv DRONE_STAGE_MACHINE

- name: build
  image: *image
  privileged: true
  commands:
  - pip install -r requirements.txt
  - pip install --index-url http://bender.brainchipinc.local:81/ --trusted-host bender.brainchipinc.local --pre -U cnn2snn akida_models
  - sphinx-build -D plot_gallery=1 -b html ./doc ./build
  volumes:
    - name: akida_chip
      path: /dev/akida0

volumes:
- name: akida_chip
  host:
    path: /dev/akida0

node:
  hw: gpu-nsoc_v2

---
kind: pipeline
name: build-doc-tf2.10


trigger:
  cron:
    - nightly

platform:
  os: linux
  arch: amd64

defs:
  image: &image bender:5000/doc_build_tf2.10:akida-gpu_tf210

steps:
- name: report host name
  image: *image
  commands:
  - printenv DRONE_STAGE_MACHINE

- name: build
  image: *image
  privileged: true
  commands:
  # explicit install to resolve Tensorflow dependencies
  - pip install protobuf==3.19.6 tensorflow-datasets==4.9.0 tensorflow-metadata==1.13.0
  - pip install -r requirements.txt
  - sphinx-build -D plot_gallery=1 -b html ./doc ./build
  volumes:
    - name: akida_chip
      path: /dev/akida0

volumes:
- name: akida_chip
  host:
    path: /dev/akida0

node:
  hw: gpu-nsoc_v2

depends_on:
  - check-style
