ARG TF_VERSION=2.8.0-gpu
FROM tensorflow/tensorflow:$TF_VERSION
MAINTAINER EF <efromme@brainchip.com>

RUN python -m pip install --upgrade pip
RUN pip install sphinx~=4.2.0 \
                sphinx_rtd_theme \
                sphinx-gallery \
                autodocsumm \
                imageio==2.15.0 \
                imbalanced-learn \
                jupyter \
                matplotlib \
                pandas \
                progressbar \
                scikit-learn \
                tensorflow-datasets \
                tabulate \
                trimesh \
                pytest \
                pytest-xdist

ENV TF_FORCE_GPU_ALLOW_GROWTH=true

CMD ["/bin/bash"]