FROM python:3.7

RUN pip install sphinx sphinx_rtd_theme sphinx-gallery autodocsumm \
                tensorflow==2.0 imageio imblearn jupyter matplotlib numpy \
                pandas progressbar sklearn tensorflow-datasets pytest \
                pytest-xdist

CMD ["/bin/bash"]

