ARG TF_VERSION=2.6.1-gpu
FROM tensorflow/tensorflow:$TF_VERSION
MAINTAINER EF <efromme@brainchip.com>

RUN python -m pip install --upgrade pip
RUN pip install sphinx~=4.2.0 \
                sphinx_rtd_theme \
                sphinx-gallery \
                autodocsumm \
                imageio~=2.9.0 \
                imbalanced-learn~=0.8.1 \
                jupyter~=1.0.0 \
                matplotlib~=3.3.4 \
                pandas~=1.1.5 \
                progressbar~=2.5 \
                scikit-learn~=0.24.2 \
                tensorflow-datasets~=4.4.0 \
                pytest \
                pytest-xdist

ENV TF_FORCE_GPU_ALLOW_GROWTH=true

CMD ["/bin/bash"]