ARG TF_VERSION=2.4.0-gpu
FROM tensorflow/tensorflow:$TF_VERSION
MAINTAINER EF <efromme@brainchip.com>

RUN python -m pip install --upgrade pip
RUN pip install sphinx sphinx_rtd_theme sphinx-gallery autodocsumm \
                imageio imblearn jupyter matplotlib pandas progressbar \
                sklearn tensorflow-datasets pytest pytest-xdist

ENV TF_FORCE_GPU_ALLOW_GROWTH=true

CMD ["/bin/bash"]